stages:
  - test
  - build
  - package
  - deploy

variables:
  PYTHON_VERSION: "3.8"

# Test stage - run on all branches
test:python:
  stage: test
  image: python:${PYTHON_VERSION}
  before_script:
    - apt-get update -qq && apt-get install -y -qq python3-tk
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python3 -m py_compile hal_gui.py
    - python3 -m py_compile hal_gui_no_pil.py
    - python3 -m py_compile hal_debug.py
    - python3 test_pil.py --test-only || true  # Allow PIL tests to fail
    - echo "✓ Python syntax validation passed"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Build stage - compile and validate
build:validate:
  stage: build
  image: python:${PYTHON_VERSION}
  before_script:
    - apt-get update -qq && apt-get install -y -qq python3-tk
  script:
    - chmod +x *.sh
    - ./test_hal.sh --validate-only || true
    - echo "✓ Build validation completed"
  artifacts:
    paths:
      - "*.py"
      - "*.sh"
      - "assets/"
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Package stage - create distribution
package:release:
  stage: package
  image: ubuntu:20.04
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq make tar gzip
  script:
    - make clean
    - make package
    - ls -la *.tar.gz*
    - echo "✓ Distribution package created"
  artifacts:
    paths:
      - "hal9000-interface-*.tar.gz"
      - "hal9000-interface-*.tar.gz.sha256"
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Deploy stage - create release
deploy:release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Creating release for $CI_COMMIT_TAG"
  release:
    name: 'HAL 9000 Interface $CI_COMMIT_TAG'
    description: |
      ## HAL 9000 - Amazon Q Interface $CI_COMMIT_TAG
      
      A retro computer interface inspired by HAL 9000 from "2001: A Space Odyssey".
      
      ### Features
      - 🎨 Dual color themes (Green/Amber)
      - 🖥️ IBM terminal fonts
      - 🤖 Amazon Q CLI integration
      - 💻 Shell mode with tab completion
      - 📊 Authentic HAL 9000 aesthetic
      
      ### Quick Install
      ```bash
      wget $CI_PROJECT_URL/-/releases/$CI_COMMIT_TAG/downloads/hal9000-interface-2.0.tar.gz
      tar -xzf hal9000-interface-2.0.tar.gz
      cd hal9000-interface-2.0
      ./install.sh
      ```
      
      ### Changes
      See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
    tag_name: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'HAL 9000 Interface Package'
          url: '$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_TAG/raw/hal9000-interface-2.0.tar.gz?job=package:release'
        - name: 'Package Checksum'
          url: '$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_TAG/raw/hal9000-interface-2.0.tar.gz.sha256?job=package:release'
  rules:
    - if: $CI_COMMIT_TAG

# Manual deployment for testing
deploy:manual:
  stage: deploy
  script:
    - echo "Manual deployment triggered"
    - echo "Package available at: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=package:release"
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
